2021-01-08 18:02:41,812:DEBUG:certbot._internal.main:certbot version: 1.11.0
2021-01-08 18:02:41,812:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2021-01-08 18:02:41,812:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--email', 'fouad992@gmail.com', '--agree-tos', '--no-eff-email', '-d', 'foushware.hopto.org']
2021-01-08 18:02:41,812:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-01-08 18:02:41,843:DEBUG:certbot._internal.log:Root logging level set at 20
2021-01-08 18:02:41,844:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2021-01-08 18:02:41,845:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2021-01-08 18:02:41,850:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7f310ffda5b0>
Prep: True
2021-01-08 18:02:41,851:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7f310ffda5b0> and installer None
2021-01-08 18:02:41,851:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2021-01-08 18:02:41,855:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/108796628', new_authzr_uri=None, terms_of_service=None), f13f427ca6f9078888672f74e828b195, Meta(creation_dt=datetime.datetime(2021, 1, 8, 17, 37, 49, tzinfo=<UTC>), creation_host='9abea44eeeef', register_to_eff=None))>
2021-01-08 18:02:41,856:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2021-01-08 18:02:41,859:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2021-01-08 18:02:43,815:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2021-01-08 18:02:43,818:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 08 Jan 2021 18:02:43 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "Ky7lVzXQTis": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2021-01-08 18:02:43,820:DEBUG:certbot.display.util:Notifying user: Requesting a certificate for foushware.hopto.org
2021-01-08 18:02:44,003:DEBUG:certbot.crypto_util:Generating RSA key (2048 bits): /etc/letsencrypt/keys/0004_key-certbot.pem
2021-01-08 18:02:44,006:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0004_csr-certbot.pem
2021-01-08 18:02:44,007:DEBUG:acme.client:Requesting fresh nonce
2021-01-08 18:02:44,007:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2021-01-08 18:02:44,327:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2021-01-08 18:02:44,329:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 08 Jan 2021 18:02:44 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 01046xdH2kPdhn-AfMGPBaRln62vgtK1VhsO975DdWYT9UI
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2021-01-08 18:02:44,329:DEBUG:acme.client:Storing nonce: 01046xdH2kPdhn-AfMGPBaRln62vgtK1VhsO975DdWYT9UI
2021-01-08 18:02:44,330:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "foushware.hopto.org"\n    }\n  ]\n}'
2021-01-08 18:02:44,335:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTA4Nzk2NjI4IiwgIm5vbmNlIjogIjAxMDQ2eGRIMmtQZGhuLUFmTUdQQmFSbG42MnZndEsxVmhzTzk3NURkV1lUOVVJIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIifQ",
  "signature": "lKSMojBVf7nI1vRaF9FoAewoBlnw6WOo2fllcYMAtJrF77Ddv20EAg2ysKStBpT6RlkqteU2ef_4TZw8a4zCrzCcVwnsBwQcJy43s-I2HmA-3JsgbwviO5VrixEf30_Jb1lQKe3rge4M6sBVEacxrtExm0pPdraV9CL31jdXA5dfDd634kFrAB0Kcv9D_6NoDu0aUbGHgpZWJAFCHKOOEIRPbPh3VhGUfIyT-KLUjLlsUALowK3iSdjQe-iVbp5jIocQdZH1WtsRdzGwrP7BN8gdWdujaLLa8S587vQtw1l5LxB6DnDkNocJ86xjfs2aNFqT6T3s0fCMqLzk0VK8cw",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImZvdXNod2FyZS5ob3B0by5vcmciCiAgICB9CiAgXQp9"
}
2021-01-08 18:02:45,397:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 340
2021-01-08 18:02:45,398:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Fri, 08 Jan 2021 18:02:44 GMT
Content-Type: application/json
Content-Length: 340
Connection: keep-alive
Boulder-Requester: 108796628
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/108796628/7199403926
Replay-Nonce: 0103znMFmdqmcCk4YPA-nou_eh4mZDo2tFo2xXWTJSgR374
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2021-01-15T17:56:07Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "foushware.hopto.org"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/9922903243"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/108796628/7199403926"
}
2021-01-08 18:02:45,398:DEBUG:acme.client:Storing nonce: 0103znMFmdqmcCk4YPA-nou_eh4mZDo2tFo2xXWTJSgR374
2021-01-08 18:02:45,398:DEBUG:acme.client:JWS payload:
b''
2021-01-08 18:02:45,401:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/9922903243:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTA4Nzk2NjI4IiwgIm5vbmNlIjogIjAxMDN6bk1GbWRxbWNDazRZUEEtbm91X2VoNG1aRG8ydEZvMnhYV1RKU2dSMzc0IiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My85OTIyOTAzMjQzIn0",
  "signature": "woQkuRW7ym9sAo0t4cU9-EYv3boL0Il21DObD22Wg20PN1Eed6AvPKZGSqaWTY7gI8VKS9FwW2yVsDj5rSu_MJuUxwgNhUpOcpmH909KRWEYUXV-IHglkd2Wuk5DkIZJ2ShHrk6rNxhfmmWTSu7mZuaUuPgHUUXAOrc4kVzqdlT1Xk6asH_gweLyEg4G3ZCw8ihgodBMuL5g9hHQj9BARIHfsHMiGGWu4BOKJ54l4oiFtScoUQkyaHn_YO4MvaAG1-NyTyYmi6-b_zQDMcGb6BTyxl5BDnPgA4iPOJlzqKG-mYYqvB4FnvpR_jh7GTHhAS5cvRksa8S_8SQxtbS5Ow",
  "payload": ""
}
2021-01-08 18:02:45,808:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/9922903243 HTTP/1.1" 200 797
2021-01-08 18:02:45,809:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 08 Jan 2021 18:02:45 GMT
Content-Type: application/json
Content-Length: 797
Connection: keep-alive
Boulder-Requester: 108796628
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0104pwHgtW1uR4kRufCvTUs4x2akZ1bvYuS8_EcnzQoGTqg
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "foushware.hopto.org"
  },
  "status": "pending",
  "expires": "2021-01-15T17:56:07Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/9922903243/KZBEDw",
      "token": "O-zMcdOJjWs29AK71Ffk07873JglaeF-s4VXY4SlyYo"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/9922903243/gbna3g",
      "token": "O-zMcdOJjWs29AK71Ffk07873JglaeF-s4VXY4SlyYo"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/9922903243/uk-xNw",
      "token": "O-zMcdOJjWs29AK71Ffk07873JglaeF-s4VXY4SlyYo"
    }
  ]
}
2021-01-08 18:02:45,810:DEBUG:acme.client:Storing nonce: 0104pwHgtW1uR4kRufCvTUs4x2akZ1bvYuS8_EcnzQoGTqg
2021-01-08 18:02:45,811:INFO:certbot._internal.auth_handler:Performing the following challenges:
2021-01-08 18:02:45,812:INFO:certbot._internal.auth_handler:http-01 challenge for foushware.hopto.org
2021-01-08 18:02:45,814:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/opt/certbot/src/certbot/certbot/_internal/plugins/webroot.py", line 81, in perform
    self._set_webroots(achalls)
  File "/opt/certbot/src/certbot/certbot/_internal/plugins/webroot.py", line 98, in _set_webroots
    new_webroot = self._prompt_for_webroot(achall.domain,
  File "/opt/certbot/src/certbot/certbot/_internal/plugins/webroot.py", line 120, in _prompt_for_webroot
    webroot = self._prompt_for_new_webroot(domain, True)
  File "/opt/certbot/src/certbot/certbot/_internal/plugins/webroot.py", line 140, in _prompt_for_new_webroot
    code, webroot = ops.validated_directory(
  File "/opt/certbot/src/certbot/certbot/display/ops.py", line 351, in validated_directory
    return _get_validated(zope.component.getUtility(interfaces.IDisplay).directory_select,
  File "/opt/certbot/src/certbot/certbot/display/ops.py", line 309, in _get_validated
    code, raw = method(message, default=default, **kwargs)
  File "/opt/certbot/src/certbot/certbot/display/util.py", line 368, in directory_select
    return self.input(message, default, cli_flag, force_interactive)
  File "/opt/certbot/src/certbot/certbot/display/util.py", line 212, in input
    ans = input_with_timeout(message)
  File "/opt/certbot/src/certbot/certbot/display/util.py", line 97, in input_with_timeout
    raise EOFError
EOFError

2021-01-08 18:02:45,815:DEBUG:certbot._internal.error_handler:Calling registered functions
2021-01-08 18:02:45,815:INFO:certbot._internal.auth_handler:Cleaning up challenges
2021-01-08 18:02:45,815:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2021-01-08 18:02:45,815:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/opt/certbot/src/certbot/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1421, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1294, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 135, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 441, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 374, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 421, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/opt/certbot/src/certbot/certbot/_internal/plugins/webroot.py", line 81, in perform
    self._set_webroots(achalls)
  File "/opt/certbot/src/certbot/certbot/_internal/plugins/webroot.py", line 98, in _set_webroots
    new_webroot = self._prompt_for_webroot(achall.domain,
  File "/opt/certbot/src/certbot/certbot/_internal/plugins/webroot.py", line 120, in _prompt_for_webroot
    webroot = self._prompt_for_new_webroot(domain, True)
  File "/opt/certbot/src/certbot/certbot/_internal/plugins/webroot.py", line 140, in _prompt_for_new_webroot
    code, webroot = ops.validated_directory(
  File "/opt/certbot/src/certbot/certbot/display/ops.py", line 351, in validated_directory
    return _get_validated(zope.component.getUtility(interfaces.IDisplay).directory_select,
  File "/opt/certbot/src/certbot/certbot/display/ops.py", line 309, in _get_validated
    code, raw = method(message, default=default, **kwargs)
  File "/opt/certbot/src/certbot/certbot/display/util.py", line 368, in directory_select
    return self.input(message, default, cli_flag, force_interactive)
  File "/opt/certbot/src/certbot/certbot/display/util.py", line 212, in input
    ans = input_with_timeout(message)
  File "/opt/certbot/src/certbot/certbot/display/util.py", line 97, in input_with_timeout
    raise EOFError
EOFError
2021-01-08 18:02:45,817:ERROR:certbot._internal.log:An unexpected error occurred:
2021-01-08 18:02:45,817:ERROR:certbot._internal.log:EOFError
